services:
    upload.annotation_reader:
        class: Devart\UploadBundle\Annotation\UploadAnnotationReader
        arguments: ["@annotations.reader"]
    upload.subscriber:
        class: Devart\UploadBundle\Listener\UploadSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default}
